#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails


def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  sales_by_year = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # Also handle max sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    # Also handle most popular car_year
    year = item["car"]["car_year"]
    if year not in sales_by_year:
      sales_by_year[year] = 0
    sales_by_year[year] += item["total_sales"]
  max_year_sales = sorted(sales_by_year.items(), key=lambda x: x[1], reverse=True)[0]

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(
      max_year_sales[0], max_year_sales[1])
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = []
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  # Sort by total sales (reverse order)
  table_data = sorted(table_data, key=lambda x: x[3], reverse=True)
  table_data.insert(0, ["ID", "Car", "Price", "Total Sales"])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # Turn this into a PDF report
  title = "Sales summary for last month"
  reports.generate("/tmp/cars.pdf", title, "<br/>".join(summary), cars_dict_to_table(data))
  # Send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "student-03-13227d530341@example.com"
  subject = title
  body = "\n".join(summary)
  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
